name: Build and Run ARM64 Rust Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker (optional)
      run: echo "No DockerHub login required if not pushing"

    - name: Build ARM64 image using Buildx
      run: |
          docker buildx build \
          --platform linux/arm64 \
          -f Dockerfile.arm64 \
          -t rustifi-arm64 \
          --load .
    - name: Run ARM64 container
      run: |
        docker run --rm --platform linux/arm64 rustifi-arm64

